language: php

php:
  - 5.3
  - 5.4
  - 5.5
#  - hhvm

#matrix:
#  allow_failures:
#    - hhvm

branches:
  only:
    - master
    - develop

before_script:
  - curl -s https://getcomposer.org/installer | php
  - $(which php) composer.phar --dev install

script:
  - vendor/bin/phpunit